# Generated by Django 4.1.7 on 2025-12-23 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0005_about_socialmedialinks'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SocialMediaLinks',
            new_name='SocialMediaLink',
        ),
        migrations.AlterModelOptions(
            name='about',
            options={'verbose_name_plural': 'About'},
        ),
    ]
